apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev
namePrefix: dev-

resources:
  - ../../base

patches:
  - path: replica-patch.yaml
  - path: configmap-patch.yaml
  - path: ingress-patch.yaml

labels:
  - pairs:
      environment: dev
