apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev
namePrefix: dev-

bases:
  - ../../base

patchesStrategicMerge:
  - replica-patch.yaml
  - configmap-patch.yaml
  - ingress-patch.yaml

commonLabels:
  environment: dev
